--- 

- name: Dump | Fa una copia de la DB
  mysql_db:
    state: dump
    name: '{{ wordpress_db }}'
    target: /tmp/dump.sql

- name: Copia | Directori wp-content
  command: cp -a /var/www/projecte/wordpress/wp-content/. /var/www/backup/ creates="/var/www/backup/"
