---

# Master Tasks per instal·lar i configurar MySql & WORDPRESS

- name: PHP | Instal·lació
  # Tot el qye està en "{{ }}", fà referència a alguna cosa.
  # Pot estar seguit en un array o bé al directori de vars 
  apt: 
    pkg: ['php', 'php-common', 'php-mysql', 'php-xml', 'php-mbstring', 'php-xmlrpc', 'php-fpm', 'php-curl', 'unzip', 'wget'] 
    state: present
  
  # Els tags són a mode de filtre per als playbooks. 
  # Podem només llençar un tag determinat.    


- name: MySQL | Instal·lació i configuració de la DB
  # Amb un "include", li especifiquem que ha d'executar un altre fitxer
  include_tasks: DB.yml

- name: WordPress | Descarregà i configuració
  include_tasks: wordpress.yml

- name: Unistall | Per a desinstal·lar
  import_tasks: uninstall.yml
  when: uninstall == "yes"

- name: Dump | Copia de Seguretat DB
  import_tasks: dump_DB.yml
