---
# tasks file for apache

- name: update
  apt:
    update_cache: yes

- name: install apache2
  apt: 
    name: apache2 
    state: present

- name: restart apache2
  service: 
    name: apache2
    state: restarted

- name: create domain drectory
  file:
    path: "/var/www/{{ http_host }}"
    state: directory
    owner: '{{ ansible_env.USER }}'
    mode: '0755'

- name: copy index test page
  template:
    src: "templates/index.html.j2"
    dest: "/var/www/{{ http_host }}/index.html"

- name: set up Apache virtuahHost
  template:
    src: "templates/apache.conf.j2"
    dest: "/etc/apache2/sites-available/{{ http_conf }}"

- name: Enable vhost
  command: a2ensite '{{ http_host }}' 
       
- apache2_module:
    state: absent
    name: '000-default.conf'

- name: host alias
  lineinfile:
    path: /etc/hosts
    insertafter: '127.0.0.1 localhost'
    line: '127.0.1.1 projecte.com'

- name: reload apache2
  service:
    name: apache2
    state: reloaded
